/* Generated By:JavaCC: Do not edit this line. CTBParser200Constants.java */
public interface CTBParser200Constants {

  int EOF = 0;
  int COMMENT = 5;
  int NUMBER = 32;
  int ID = 33;
  int STRING = 34;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"VERSION=\"",
    "\"NAME=\"",
    "\"CLASS=\"",
    "\"TYPE=\"",
    "\"OPTION=\"",
    "\"VALUE=\"",
    "\"XPOS=\"",
    "\"YPOS=\"",
    "\"WIDTH=\"",
    "\"HEIGHT=\"",
    "\"OUT=\"",
    "\"IN=\"",
    "\"<CBF\"",
    "\">\"",
    "\"</CBF>\"",
    "\"<CDF\"",
    "\"</CDF>\"",
    "\"<EVENT\"",
    "\"</EVENT>\"",
    "\"<DIAGRAM\"",
    "\"</DIAGRAM>\"",
    "\"<MODULE\"",
    "\"/>\"",
    "\"</MODULE>\"",
    "\"E\"",
    "\"<ROUTE\"",
    "<NUMBER>",
    "<ID>",
    "<STRING>",
  };

}
