/* Generated By:JavaCC: Do not edit this line. CTBParser100Constants.java */
public interface CTBParser100Constants {

  int EOF = 0;
  int COMMENT = 5;
  int Event = 6;
  int Diagram = 7;
  int Module = 8;
  int Name = 9;
  int Option = 10;
  int Class = 11;
  int Type = 12;
  int Pos = 13;
  int Size = 14;
  int Value = 15;
  int Dataflow = 16;
  int To = 17;
  int NUMBER = 22;
  int ID = 23;
  int STRING = 24;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<COMMENT>",
    "\"Event\"",
    "\"Diagram\"",
    "\"Module\"",
    "\"name\"",
    "\"option\"",
    "\"class\"",
    "\"type\"",
    "\"pos\"",
    "\"size\"",
    "\"value\"",
    "\"Dataflow\"",
    "\"to\"",
    "\"{\"",
    "\"}\"",
    "\"E\"",
    "\".\"",
    "<NUMBER>",
    "<ID>",
    "<STRING>",
  };

}
