#!/Cygnus/B19/H-i386-cygwin32/bin/sh
rm *.class
rm field/*.class
rm j3d/*.class
rm node/*.class
rm image/*.class
rm parser/vrml97/*.class
rm parser/wavefront/*.class
rm parser/autodesk/*.class
rm parser/sense8/*.class
rm parser/threedsystems/*.class
rm parser/x3d/*.class
rm route/*.class
rm util/*.class
